var codingProjects = [
  {
    title: 'sdcaulley.com',
    projectUrl: 'http://sdcaulley.com',
    projectImage: 'img/sdcaulleyScreenShot.png',
    projectCompleted: '2014-02-25',
    projectDescription: "<p>Wordpress blog featuring theology</p><p>Lucas ipsum dolor sit amet darth owen mara calamari grievous twi'lek han bespin coruscant antilles. Binks mon dooku qui-gon k-3po maul dooku. Yoda windu jade fisto moff ponda. Naboo mustafar darth kashyyyk. Hutt solo binks grievous antilles. Skywalker obi-wan moff wampa moff fisto mon. Organa mon skywalker qui-gonn dooku jinn calamari fisto. Kessel kenobi yoda han dantooine grievous vader calamari. Leia luke kenobi mandalore moff jinn maul jar. Lando anakin mara bothan k-3po organa. Skywalker skywalker mothma luke secura grievous wedge dagobah biggs.</p><p>Darth darth kashyyyk qui-gon wedge. Tusken raider kashyyyk greedo dantooine jawa dagobah fett windu. Antilles tusken raider jinn utapau coruscant. Mothma antilles kessel luke. Sidious coruscant kessel bothan maul padmé luke biggs hoth. Ackbar mon darth wedge chewbacca greedo jade tatooine binks. Windu padmé han darth sith luke. Kashyyyk solo hoth moff coruscant jawa anakin sidious. Coruscant secura wampa windu moff jabba mandalore. Yoda sith calamari secura calrissian mandalorians. Vader aayla jango kamino windu darth yavin obi-wan hutt.</p><p>Jango yavin naboo skywalker tusken raider. Vader moff fisto jade luke thrawn. Fett utapau wedge sebulba kit anakin endor. Darth moff obi-wan skywalker jango secura greedo. Dantooine skywalker darth organa binks. Hutt dooku dantooine owen solo. Tatooine yoda antilles tusken raider mon cade moff. Anakin anakin hutt ackbar mace grievous palpatine hoth han. Mon boba antilles dagobah leia lando ackbar skywalker. Mon yoda mon skywalker moff. Amidala skywalker boba mandalore wedge cade. Moff ackbar organa ewok chewbacca anakin sidious coruscant skywalker.</p><p>Alderaan thrawn windu grievous jade yoda. Lando boba dagobah mon qui-gonn. Hutt solo skywalker moff skywalker dooku moff skywalker hutt. Lando kessel lando antilles han coruscant hutt wicket boba. Sith gamorrean dooku kashyyyk grievous bespin droid. Alderaan ackbar calrissian lando anakin jinn. Ewok ahsoka fett kenobi. Luke wedge wedge skywalker mon calamari. Moff mon fett hoth windu yavin kenobi. Antilles dagobah organa jabba. Mace kashyyyk antilles han boba vader darth. Coruscant mon k-3po bespin padmé.</p><p>Calrissian mustafar wedge secura calrissian darth. Darth darth palpatine maul ackbar coruscant antilles. Han moff fett binks darth. Windu luke moff wicket padmé. Calrissian tusken raider r2-d2 jar maul kessel jinn grievous. Darth leia alderaan binks fett ackbar secura c-3p0. Darth fett darth skywalker fett yoda hutt palpatine. Kenobi sith mandalore lars. Skywalker vader antilles tatooine sidious leia moff. Mandalorians kit organa jabba binks. Ackbar grievous lars sidious obi-wan anakin skywalker antilles.</p>",
    skillShowcased: ['Wordpress', 'Themeing']
  },
  {
    title: 'sdcaulleyoriginals.com',
    projectUrl: 'http://sdcaulleyoriginals.com',
    projectImage: 'img/sdcOriginalsScreenShot.png',
    projectCompleted: '2015-04-15',
    projectDescription: "<p>Wordpress blog for crafting and sewing</p><p>So these are my replacements. A dandy and a clown. Shut up, K-9! Do you have to talk like children? What is it that makes you so ashamed of being a grown-up? I don't suppose we'll ever know if we actually succeeded. But at worst, we failed doing the right thing, as opposed to succeeding in doing the wrong. Your hips are fine, you're built like a man! Good grief.... It's a Stegosaurus! Jamie, remind me to give you a lesson in tying knots, sometime. It's rather a pity, in a way...now the universe is down to 699 wonders.</p><p>Doctor no more. Adric? People who talk about infallibility are usually on very shaky ground. Change, my dear. And it seems not a moment too soon. Goodbye, Clara. It may be irrational of me, but human beings are my favorite species. Pure mathematics can not lie! I reversed the polarity of the neutron flow. I need...I need...I need... fish fingers and custard! Go and be the Doctor that I could never be. You don't understand so you find excuses. There's something that doesn't make sense. Let's go and poke it with a stick.</p><p>Well, I would say that that person would be an egomaniac, need, game-player sort of person. It's all right up to the eyebrows. Then it goes haywire. Well, I'll tell you something that should be of vital interest to you.…That you, Sir, are a NITWIT! Jo, did you fail Latin as well as science? Not allowed? Not allowed? Me, I’m allowed everywhere. The world's about to end, and here I am, stuck in traffic. Old ladies die all the time. It's practically in the job description. Good grief.... It's a Stegosaurus!</p><p>This is a situation that requires tact and finesse. Fortunately, I am blessed with both. I don't need a sword. Because I'm the Doctor ... and this is my spoon. I don't know. But I'd probably blame the English. I just have one question… do you know how to fly this thing? Oh, the pointing again! They're screwdrivers! What are you going to do? Assemble a cabinet at them? My last incarnation…oh, I was never happy with that one. It had a sort of feckless 'charm' which simply wasn't me. There's something else I've always wanted to say: Allons-y, Alonso!</p><p>Your wish is my command. But be careful what you wish for. The least important things, sometimes my dear boy, lead to the greatest discoveries. It's times like this I wish I still had my scarf. Oh, my giddy aunt! Allow me to congratulate you, sir. You have the most totally closed mind that I've ever encountered. Now, don't antagonize her. I love a happy medium! Oh, I always rip out the last page of a book. Then it doesn't have to end. I hate endings! Run. Are you taller? Why? Do you have to reach a high shelf?</p>",
    skillShowcased: ['Wordpress', 'Themeing']
  },
  {
    title: 'Market Analysis Application',
    projectUrl: 'https://sdcaulley.github.io/market-analysis-app/',
    projectImage: 'img/busMallScreenShot.png',
    projectCompleted: '2016-08-03',
    projectDescription: "<p>JavaScript application for recording user votes.</p><p>These are the voyages of the Starship Enterprise. Its continuing mission, to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no one has gone before. We need to neutralize the homing signal. Each unit has total environmental control, gravity, temperature, atmosphere, light, in a protective field. Sensors show energy readings in your area. We had a forced chamber explosion in the resonator coil. Field strength has increased by 3,000 percent.</p><p>Now what are the possibilities of warp drive? Cmdr Riker's nervous system has been invaded by an unknown microorganism. The organisms fuse to the nerve, intertwining at the molecular level. That's why the transporter's biofilters couldn't extract it. The vertex waves show a K-complex corresponding to an REM state. The engineering section's critical. Destruction is imminent. Their robes contain ultritium, highly explosive, virtually undetectable by your transporter.</p><p>Sensors indicate human life forms 30 meters below the planet's surface. Stellar flares are increasing in magnitude and frequency. Set course for Rhomboid Dronegar 006, warp seven. There's no evidence of an advanced communication network. Total guidance system failure, with less than 24 hours' reserve power. Shield effectiveness has been reduced 12 percent. We have covered the area in a spherical pattern which a ship without warp drive could cross in the given time.</p><p>Deflector power at maximum. Energy discharge in six seconds. Warp reactor core primary coolant failure. Fluctuate phaser resonance frequencies. Resistance is futile. Recommend we adjust shield harmonics to the upper EM band when proceeding. These appear to be some kind of power-wave-guide conduits which allow them to work collectively as they perform ship functions. Increase deflector modulation to upper frequency band.</p><p>Run a manual sweep of anomalous airborne or electromagnetic readings. Radiation levels in our atmosphere have increased by 3,000 percent. Electromagnetic and subspace wave fronts approaching synchronization. What is the strength of the ship's deflector shields at maximum output? The wormhole's size and short period would make this a local phenomenon. Do you have sufficient data to compile a holographic simulation?</p><p>Resistance is futile.</p>",
    skillShowcased: ['JavaScript', 'HTML', 'CSS']
  },
];

var category = ['Wordpress', 'JavaScript', 'HTML', 'CSS', 'Themeing'];
